package com.sherlock.mallpayment.model.order;

import java.util.Date;

public class OrderHead {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.id
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.amount
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.received
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    private Integer received;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.status
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.gmt_create
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_head.gmt_modified
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.id
     *
     * @return the value of order_head.id
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.id
     *
     * @param id the value for order_head.id
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.amount
     *
     * @return the value of order_head.amount
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.amount
     *
     * @param amount the value for order_head.amount
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.received
     *
     * @return the value of order_head.received
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    public Integer getReceived() {
        return received;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.received
     *
     * @param received the value for order_head.received
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    public void setReceived(Integer received) {
        this.received = received;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.status
     *
     * @return the value of order_head.status
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.status
     *
     * @param status the value for order_head.status
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.gmt_create
     *
     * @return the value of order_head.gmt_create
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.gmt_create
     *
     * @param gmtCreate the value for order_head.gmt_create
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_head.gmt_modified
     *
     * @return the value of order_head.gmt_modified
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_head.gmt_modified
     *
     * @param gmtModified the value for order_head.gmt_modified
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}