package com.sherlock.mallpayment.mapper.order;

import com.sherlock.mallpayment.model.order.OrderHead;
import com.sherlock.mallpayment.model.order.OrderHeadExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_head
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    int countByExample(OrderHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_head
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    int deleteByExample(OrderHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_head
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_head
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    int insert(OrderHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_head
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    int insertSelective(OrderHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_head
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    List<OrderHead> selectByExample(OrderHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_head
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    OrderHead selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_head
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrderHead record, @Param("example") OrderHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_head
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    int updateByExample(@Param("record") OrderHead record, @Param("example") OrderHeadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_head
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    int updateByPrimaryKeySelective(OrderHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_head
     *
     * @mbggenerated Fri Apr 19 11:00:53 CST 2019
     */
    int updateByPrimaryKey(OrderHead record);
}