package com.sherlock.mallgoods.model.goods;

import java.util.Date;

public class Type {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.id
     *
     * @mbggenerated Wed Apr 17 17:04:40 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.no
     *
     * @mbggenerated Wed Apr 17 17:04:40 CST 2019
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.name
     *
     * @mbggenerated Wed Apr 17 17:04:40 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.gmt_create
     *
     * @mbggenerated Wed Apr 17 17:04:40 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.gmt_modified
     *
     * @mbggenerated Wed Apr 17 17:04:40 CST 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.id
     *
     * @return the value of type.id
     *
     * @mbggenerated Wed Apr 17 17:04:40 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.id
     *
     * @param id the value for type.id
     *
     * @mbggenerated Wed Apr 17 17:04:40 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.no
     *
     * @return the value of type.no
     *
     * @mbggenerated Wed Apr 17 17:04:40 CST 2019
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.no
     *
     * @param no the value for type.no
     *
     * @mbggenerated Wed Apr 17 17:04:40 CST 2019
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.name
     *
     * @return the value of type.name
     *
     * @mbggenerated Wed Apr 17 17:04:40 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.name
     *
     * @param name the value for type.name
     *
     * @mbggenerated Wed Apr 17 17:04:40 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.gmt_create
     *
     * @return the value of type.gmt_create
     *
     * @mbggenerated Wed Apr 17 17:04:40 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.gmt_create
     *
     * @param gmtCreate the value for type.gmt_create
     *
     * @mbggenerated Wed Apr 17 17:04:40 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.gmt_modified
     *
     * @return the value of type.gmt_modified
     *
     * @mbggenerated Wed Apr 17 17:04:40 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.gmt_modified
     *
     * @param gmtModified the value for type.gmt_modified
     *
     * @mbggenerated Wed Apr 17 17:04:40 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}