package com.sherlock.mallpayment.model.payment;

import java.util.Date;

public class Payment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.id
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.order_id
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.status
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.gmt_create
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payments.gmt_modified
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.id
     *
     * @return the value of payments.id
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.id
     *
     * @param id the value for payments.id
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.order_id
     *
     * @return the value of payments.order_id
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.order_id
     *
     * @param orderId the value for payments.order_id
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.status
     *
     * @return the value of payments.status
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.status
     *
     * @param status the value for payments.status
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.gmt_create
     *
     * @return the value of payments.gmt_create
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.gmt_create
     *
     * @param gmtCreate the value for payments.gmt_create
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payments.gmt_modified
     *
     * @return the value of payments.gmt_modified
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payments.gmt_modified
     *
     * @param gmtModified the value for payments.gmt_modified
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}