package com.sherlock.mallpayment.mapper.payment;

import com.sherlock.mallpayment.model.payment.Payment;
import com.sherlock.mallpayment.model.payment.PaymentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    int countByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    int deleteByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    int insert(Payment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    int insertSelective(Payment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    List<Payment> selectByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    Payment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") Payment record, @Param("example") PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    int updateByExample(@Param("record") Payment record, @Param("example") PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    int updateByPrimaryKeySelective(Payment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payments
     *
     * @mbggenerated Fri Apr 19 10:40:52 CST 2019
     */
    int updateByPrimaryKey(Payment record);
}